version: '3.3'
services:
    filepizza:
        container_name: filepizza
        ports:
            - '3333:3333'
        environment:
            - PORT=3333
        volumes:
            - '/volume1/docker/filepizza:/config'
        image: 'kern/filepizza:master'
